version: "3"
services:
  coturn:
    build: .
    #    environment:
    #      - ./turnserver.conf=/etc/turnserver.conf
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/tcp"
