services:
  coturn:
    restart: always
    ports:
      - "3478:3478"
      - "5349:5349"
      - "49160-49200:49160-49200/udp"
    volumes:
      - /etc/letsencrypt/live/bincang-visual.cloud:/certs:ro
      - ./turnserver.conf:/etc/coturn/turnserver.conf
