version: "3.8"
services:
  coturn:
    image: instrumentisto/coturn:latest
    restart: always
    network_mode: "host" # avoids NAT issues
    # we dont use ports because network_mode host
    # ports:
    #   - "3478:3478/udp"
    #   - "3478:3478"
    #   - "5349:5349"
    #   - "49160-49200:49160-49200/udp"
    volumes:
      - /etc/letsencrypt/live/bincang-visual.cloud:/certs:ro
      - ./turnserver.conf:/etc/coturn/turnserver.conf
