services:
  coturn:
    image: my-coturn
    container_name: coturn
    restart: always
    network_mode: "host" # avoids NAT issues

    # we dont use ports because network_mode host
    # ports:
    #   - "3478:3478/udp"
    #   - "3478:3478"
    #   - "5349:5349"
    #   - "49160-49200:49160-49200/udp"
    volumes:
      - /etc/letsencrypt/archive/bincang-visual.cloud:/certs:ro
      - ./turnserver.conf:/etc/coturn/turnserver.conf
