name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: TURN_USER,TURN_PASS
        script: |
          cd /home/farhan/bincang_visual_ctrn
          git reset --hard HEAD
          git pull origin master  
          
          docker compose down && docker compose up --build -d --remove-orphans