name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pull-to-deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/farhan/bincang_visual_ctrn
          git pull origin master  

          echo "Updating turnserver.conf with credentials"
          sed -i "/^# user=/c\user=${{ secrets.TURN_USER }}:${{ secrets.TURN_PASS }}" turnserver.conf       
          
          docker compose down && docker compose up --build -d --remove-orphans